#!/usr/bin/env bash
set -Eeuo pipefail

# Production bootstrap for Ubuntu/Debian servers.
# It creates a private .env with random database credentials, then builds the
# checked-out source so the repaired code is deployed instead of an old image.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

log() { printf '\033[1;36m[deploy]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[deploy] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

if [[ "$(uname -s)" != "Linux" ]]; then
  die "This script is for Linux servers."
fi

SUDO=""
if [[ "$(id -u)" -ne 0 ]]; then
  command -v sudo >/dev/null 2>&1 || die "Run as root or install sudo first."
  SUDO=sudo
fi

install_docker() {
  command -v apt-get >/dev/null 2>&1 || die "apt-get not found; install Docker Engine and Compose first."
  log "Installing Docker, Compose, Git, and OpenSSL"
  $SUDO apt-get update
  $SUDO apt-get install -y docker.io git openssl ca-certificates curl \
    docker-compose-plugin 2>/dev/null || \
    $SUDO apt-get install -y docker.io git openssl ca-certificates curl docker-compose-v2
  $SUDO systemctl enable --now docker
}

if ! command -v docker >/dev/null 2>&1; then
  install_docker
fi

if ! docker compose version >/dev/null 2>&1 && ! command -v docker-compose >/dev/null 2>&1; then
  install_docker
fi

if ! docker info >/dev/null 2>&1; then
  # A non-root user may not yet have the docker group in its current shell.
  if [[ -n "$SUDO" ]]; then
    log "Docker socket access is unavailable; deployment will use sudo"
  else
    die "Docker is not ready; check: systemctl status docker"
  fi
fi

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
  fi
}

if [[ ! -f .env ]]; then
  umask 077
  MYSQL_SECRET="$(random_secret)"
  REDIS_SECRET="$(random_secret)"
  cat > .env <<EOF
# Generated by deploy_server.sh. Keep this file private.
MYSQL_ROOT_PASSWORD=${MYSQL_SECRET}
MYSQL_DATABASE=xianyu_data
MYSQL_USER=xianyu
MYSQL_PASSWORD=${MYSQL_SECRET}
REDIS_PASSWORD=${REDIS_SECRET}
REDIS_DB=0

FRONTEND_PORT=9000
BACKEND_WEB_PORT=8089
WEBSOCKET_PORT=8090
SCHEDULER_PORT=8091
IMAGE_REGISTRY=registry.cn-shanghai.aliyuncs.com/zhinian-software
IMAGE_TAG=latest

# First boot is manual: authorize the account and confirm it is online first.
AUTO_START_WEBSOCKET=false
AUTO_START_CRAWL_JOBS=false
CAPTCHA_DRISSIONPAGE_FALLBACK_ENABLED=true
CAPTCHA_DRISSIONPAGE_TIMEOUT=25
CAPTCHA_DRISSIONPAGE_HEADLESS=true
SQL_ECHO=false
LOG_LEVEL=INFO
TOKEN_CACHE_TTL_MIN_HOURS=5
TOKEN_CACHE_TTL_MAX_HOURS=10
ACCESS_TOKEN_EXPIRE_MINUTES=1440
REFRESH_TOKEN_EXPIRE_MINUTES=10080
REDELIVERY_INTERVAL=5
RATE_INTERVAL=20
MAX_CAPTCHA_CONCURRENT=2
FRONTEND_PUBLIC_URL=
BACKEND_WEB_PUBLIC_URL=
EOF
  chmod 600 .env
  log "Generated random database/cache passwords in .env (mode 600)"
else
  if grep -Eq 'MYSQL_PASSWORD=xianyu@2026|REDIS_PASSWORD=xianyu@2026|MYSQL_ROOT_PASSWORD=xianyu@2026' .env; then
    die ".env still uses the default database password; replace it first."
  fi
  chmod 600 .env
  log "Reusing existing .env; account data and session settings are preserved"
fi

# Repository files may have CRLF when copied from Windows.
sed -i 's/\r$//' build.sh deploy.sh

MODE="${DEPLOY_MODE:-source}"
if [[ "$MODE" == "source" ]]; then
  DEPLOY_CMD=(bash "$ROOT_DIR/build.sh" rebuild)
elif [[ "$MODE" == "remote" ]]; then
  DEPLOY_CMD=(bash "$ROOT_DIR/deploy.sh")
else
  die "DEPLOY_MODE must be source or remote"
fi
if [[ -n "$SUDO" ]] && ! docker info >/dev/null 2>&1; then
  DEPLOY_CMD=(sudo "${DEPLOY_CMD[@]}")
fi

log "Building images and starting services"
"${DEPLOY_CMD[@]}"

cat <<'EOF'

After the first boot:
1. Open http://SERVER_IP:9000 and complete admin login plus QR/slider.
2. Confirm the account is connected/running, then edit .env:
   AUTO_START_WEBSOCKET=true
   AUTO_START_CRAWL_JOBS=true
3. Run: bash build.sh start

Diagnostics:
  bash build.sh status
  docker logs --tail 200 xianyu-websocket
  curl -fsS http://127.0.0.1:8089/health
EOF
